#! /bin/bash
# (al is 't alleen maar om m'n syntax highlighting goed te krijgen.. [BvS])

# lib_ldap			- de backup-scripts voor ldap
###############################################################################

#
# ldap_backup - maak een backup van alle ldap databases
#
function ldap_backup {
	# vraag de lijst met databases op
	while read -r userdn passwd
	do
		if [ "_${userdn:0:1}" != "#" -a "_${passwd}" != "_" ]; then
			echo "Dumping ldap database: '${userdn}'"
			TOFILE="ldap_${DATEFIX}_${userdn}.ldap"

			"${BASEDIR}/bin/rmt-client.pl" "${TODIR}/${TOFILE}${C_TAG}${E_TAG}" \
				echo "${passwd}" \| ldapsearch -x -D "${userdn}" -W \
					$COMPRESS $ENCRYPT \
				|| { touch "${SNAPSHOTDIR}/error"; echo 'ldap backup failed.'; }
		fi
	done < "${CONFDIR}/ldap/ldap.conf"
}

#
# clean_ldap - ruimt tijdelijke bestanden op. wordt eens per week of maand
#               aangeroepen.
#
function ldap_weekly {
	true
}

function ldap_monthly {
	true
}
