#! /bin/bash
# voor bas(h) z'n syntax highlighting


#
# backup postgres databases.
#

function pgsql_backup {
	# defaults
	export PGUSER=postgres
	export PGPASSFILE=''

	# load config
	if [ -f "${CONFDIR}/pgsql/pgsql.conf" ] ; then
		. "${CONFDIR}/pgsql/pgsql.conf"
	fi

	# do backup
	PG_SH="su $PGUSER"
	if [ "x$PGPASSFILE" != 'x' ]; then
		PG_SH="sh"
	fi

	$PG_SH -c '/usr/bin/psql -t -d template1 -c "SELECT datname FROM pg_database ORDER BY datname"' | sed 's/^ *//;/^$/d' | (
		while read -r PGSQL_DB
		do
			if ! grep -Fxq "${PGSQL_DB}" "${CONFDIR}/pgsql/pgsql.exclude"
			then
				echo "Dumping pgsql database: '${PGSQL_DB}'";
				export PGSQL_DB

				if [ "${HOSTNAME_TAG}x" == "x" ]; then 
				    TOFILE="pgsql_${DATEFIX}_${PGSQL_DB}.sql"
				else
				    TOFILE="pgsql_${DATEFIX}_${HOSTNAME_TAG}_${PGSQL_DB}.sql"
				fi

				"${BASEDIR}/bin/rmt-client.pl" "${TODIR}/${TOFILE}${C_TAG}${E_TAG}" \
					$PG_SH -c '/usr/bin/pg_dump "${PGSQL_DB}"' $COMPRESS $ENCRYPT \
					|| { touch "${SNAPSHOTDIR}/error"; echo 'pgsql dump failed.'; }
			fi
		done
	) 

	if [ "${HOSTNAME_TAG}x" == "x" ]; then 
	    TOFILE="pgsql_${DATEFIX}.sql"
	else
	    TOFILE="pgsql_${DATEFIX}_${HOSTNAME_TAG}.sql"
	fi

	PG_BIN=''
	if [ -d '/usr/lib/postgresql/bin' ]; then
		PG_BIN='/usr/lib/postgresql/bin'
	elif [ -d '/usr/lib/postgresql/8.3/bin' ]; then
		PG_BIN='/usr/lib/postgresql/8.3/bin'
	elif [ -d '/usr/lib/postgresql/8.2/bin' ]; then
		PG_BIN='/usr/lib/postgresql/8.2/bin'
	elif [ -d '/usr/lib/postgresql/8.1/bin' ]; then
		PG_BIN='/usr/lib/postgresql/8.1/bin'
	elif [ -d '/usr/lib/postgresql/7.4/bin' ]; then
		PG_BIN='/usr/lib/postgresql/7.4/bin'
	else
		touch "${SNAPSHOTDIR}/error"
		echo "/usr/lib/postgresql/bin path not found!"
		false
	fi

	"${BASEDIR}/bin/rmt-client.pl" "${TODIR}/${TOFILE}${C_TAG}${E_TAG}" \
		$PG_SH -c "$PG_BIN/pg_dumpall -g" $COMPRESS $ENCRYPT \
		|| { touch "${SNAPSHOTDIR}/error"; echo 'pgsql dump failed.'; }
}

#
# clean_pgsql - ruimt tijdelijke bestanden op. wordt eens per week of maand
#               aangeroepen.
#
function pgsql_weekly {
	true
}

function pgsql_monthly {
	true
}
