#! /bin/bash
#
# slapd          snt-backup plugin for the slapd ldap server
# 
# Author:        Rien Broekstra <rien@rename-it.nl>
#
# Version:       0.22 07-Oct-2006
#
# Changelog:     0.22 -- Rien Broekstra 07-Oct-2006
#                Bugfix: filename now no longer includes = , and _ in the wrong place
#                0.21 -- Rien Broekstra 08-Sep-2006 
#                The slapd plugin now includes a path and type specification in the backup filename

. "${CONFDIR}/slapd/slapd.conf"
. "${CONFDIR}/slapd/slapd.secret"

function slapd_backup {

    echo "Dumping LDAP directory: ${LDAP_BASE}";

    if [ "${LDAP_BASE}x" = "x" ]; then
	touch "${SNAPSHOTDIR}/error"; 
	echo 'Error: LDAP_BASE is not set.';
        echo 'slapd dump failed.';
        return;
    fi;

    local TOFILE
    # Even wat tekentjes vervangen waarvan we in de war raken als ze in een filename staan
    local LDAP_BASE_FILENAME=`echo ${LDAP_BASE} | tr _ - `;
    LDAP_BASE_FILENAME=`echo ${LDAP_BASE_FILENAME} | tr = - `;
    LDAP_BASE_FILENAME=`echo ${LDAP_BASE_FILENAME} | tr , - `;

    if [ "${HOSTNAME_TAG}x" == "x" ]; then
	TOFILE="slapd_${DATEFIX}_${LDAP_BASE_FILENAME}_full.ldif"
    else
	TOFILE="slapd_${DATEFIX}_${HOSTNAME_TAG}_${LDAP_BASE_FILENAME}_full.ldif"
    fi

    # FIXME: Allow for sasl authentication
    # The binddn needs read access to everything you want to backup from the LDAP directory
    "${BASEDIR}/bin/rmt-client.pl" "${TODIR}/${TOFILE}${C_TAG}${E_TAG}" \
	/usr/bin/ldapsearch -h ${LDAP_HOST} -p ${LDAP_PORT} -b ${LDAP_BASE} -s sub "(objectClass=top)" -x -D ${LDAP_BINDDN} -w ${LDAP_BINDPW} $COMPRESS $ENCRYPT \
	|| { touch "${SNAPSHOTDIR}/error"; echo 'slapd dump failed.'; }

}

function slapd_weekly {
    true
}

function slapd_monthly {
    true
}
